# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: swift
osx_image: xcode10
xcode_workspace: Example/LinkedInSignIn.xcworkspace
xcode_scheme: LinkedInSignIn_Example
before_install:
  - gem install cocoapods
  - cd Example
  - pod install
script:
  - xcodebuild -workspace LinkedInSignIn.xcworkspace -scheme LinkedInSignIn_Example -sdk iphonesimulator12.0 clean build | xcpretty
