# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: swift
osx_image: xcode9
xcode_workspace: Example/LinkedInSignIn.xcworkspace
xcode_scheme: LinkedInSignIn_Example
before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - cd Example
  - pod install
